### ISSUE TITLE
Single FIle Output - alternate publish solution (option)

### ISSUE THREAD

**Issue by ondrovic** [djhmateer/OpenVSSolution#6]
@djhmateer  Nice update glad to see you keeping up with it, such a great solution.

I wanted a single contained .exe so I didn't have to copy .dll and to do so I updated the [OpenVSSolution.csproj](https://github.com/djhmateer/OpenVSSolution/blob/master/OpenVSSolution/OpenVSSolution.csproj) making the following changes

``` csharp
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>d</AssemblyName>
    <!-- <PublishTrimmed>false</PublishTrimmed> -->
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
</Project>
```

This will give you an single `d.exe` in the `\bin\Release\net6.0\win-x64\publish` folder just do a 

```
1. dotnet clean
2. dotnet publish -c Release -r win-x64 --self-contained
```

Cheers

**Comment by djhmateer** [comment]
Nice one - much appreciated! Sorry for the delay in getting back to you.

**Comment by ondrovic** [comment]
> Nice one - much appreciated! Sorry for the delay in getting back to you.

No worries at all
